### ISSUE TITLE
User search

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork-design-doc#10]
Ideally:
 - You could type a name in the search bar, and get a list of matches with pictures, name, bio, WoT data.
 - If the person is on the network, the search would turn them up.
 - There'd never be a false positive.

So:
 1. How do we get the ideal?
 2. How close can we get to the ideal, with the resources and time we have available?

**Comment by mixmix** [comment]
I think facebook has a good idea (though ugly execution) 

you do a search, and it searches for content, but at the top of the search there is a link which says :

[search for people]()

**Comment by pfraze** [comment]
Agree about that flow
