### ISSUE TITLE
Should the main feed view include private messages?

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork-design-doc#3]
https://github.com/ssbc/patchwork-design-doc/blob/master/requirements/view-message-feeds.md#main-feed

Currently, we enforce a strict requirement, that the main feed only includes public messages. Is this the best choice? Would it be better to have the newsfeed be a "total" view?

**Comment by mixmix** [comment]
No, this is really confusing. Direct private messages have a massively higher priority to me than casual open chat...  which is interestingly how feeds + channels feel at the moment to me

**Comment by pfraze** [comment]
The inbox would continue to serve that function - showing the messages sent to you - but the main feed would include those messages. The inbox would be a filtering down of the main feed.
