### ISSUE TITLE
Should the bookmarks view be a link in the lefthand nav of the feed, instead of a persistent column?

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork-design-doc#5]
https://github.com/ssbc/patchwork-design-doc/blob/master/requirements/view-message-feeds.md#bookmarks

Currently, the bookmarks view is a persistent column. Would it be better as an item in feed view, similar to the channels?

![bookmarks-move](https://cloud.githubusercontent.com/assets/1270099/11858051/70ab7308-a423-11e5-99e9-83f0a47c1fbf.png)

**Comment by mixmix** [comment]
I think giving them a special place that you can dip into feels really nice

**Comment by pfraze** [comment]
Could you clarify: you prefer the column, or a bookmarks view?
