### ISSUE TITLE
How should the channel view be ordered?

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork-design-doc#7]
https://github.com/ssbc/patchwork-design-doc/blob/master/requirements/view-message-feeds.md#channel

Some options:

   - Descending: Most recently created threads
   - Descending: Most recently updated threads (current)

See also https://github.com/ssbc/patchwork-design-doc/issues/2

**Comment by mixmix** [comment]
All

---

pinned channels, in alphabetical order

---

other channels, random sample of 30 with most recent activity (stops one dominating all the time)

---

find a channel

**Comment by pfraze** [comment]
That's the nav, here I'm referring to the actual messages in the channel. We may want to open another issue for that.
