### ISSUE TITLE
Should the inbox view be a link in the lefthand nav of the feed, instead of a main nav item?

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork-design-doc#8]
https://github.com/ssbc/patchwork-design-doc/blob/master/requirements/view-message-feeds.md#inbox

Currently, the Inbox is a major section of the navigation. Could we simplify the scope of the application by making it a subview of the feed?

![no-inbox-nav](https://cloud.githubusercontent.com/assets/1270099/11858107/0b0f6698-a424-11e5-8a8a-6becc9b8e088.png)

**Comment by mixmix** [comment]
ask users. I find this really wrong because Inbox feels like such a different (and more private) space to me

**Comment by pfraze** [comment]
Relates to https://github.com/ssbc/patchwork-design-doc/issues/3
