### ISSUE TITLE
Should the message-view in the feed include replies inline?

### ISSUE THREAD

**Issue by pfraze** [ssbc/patchwork-design-doc#9]
https://github.com/ssbc/patchwork-design-doc/blob/master/requirements/view-message-threads.md#view-message-threads
https://github.com/ssbc/patchwork-design-doc/blob/master/requirements/view-message-feeds.md#view-message-feeds

Currently, only the root of a message-thread is shown in a feed view. Should some of the replies be inlined below?

**Comment by mixmix** [comment]
What is the purpose of the feed?

Does the feed need to serve threads differently depending on their age / engagement? 

---

I think a feed is about finding things that a new, surprising, and relevant.
I want to connect with familiar and new (people and content).
I want to continue conversations. 

I care more about conversations that I've been involved in, or involve people I talk often with, or are getting a lot of attention? 

When there's a conversation that I've been part of, I go looking for a thread based on things like: 
- it's start point
- a salient point that has caught my attention mid-thread
- who said the first thing or made a salient point

---

This seems an area rich for experimenting and customisation. Think how reddit offer top, hot, newest, controversial. 

---

**preview ideas**- you see the progenitor comment, along with a preview of : 
a) the last comment you liked in that thread
b) a sample of the most recent comment
c) the avatars of the people in the conversation ....

**Comment by pfraze** [comment]
Yes, I think the intent of this should be previewing the conversation, and to let you skim smaller threads without having to open them. I agree that the feed is about discovery.
